### ISSUE TITLE
How to set stripe API keys

### ISSUE THREAD

**Issue by mazharoddin** [buggy/rails-saas-template#42]
Hi,
Can you please let me know how to set "STRIPE_API_KEY" and "STRIPE_PUBLISHABLE_KEY" , I tried to STRIPE_API_KEY using config/initializers/strip.rb, but its not working, moreover I see only "Stripe.api_key" is defined there, where to set "STRIPE_PUBLISHABLE_KEY" value.
Also please let me know how to sign up, I am unable to signup because signup form expecting "invite code" to be filled, but its not throwing error if I give some random value. 
Please let me know how to signup, Your help is greatly appreciated and thanks for this nice template.

**Comment by buggy** [comment]
I use environment variable to set these so that they don't need to be committed to the repository. In development I find the best approach is to have a script like this which launches the development server
```sh
#!/bin/bash
export STRIPE_API_KEY=...your api key...
export STRIPE_PUBLISHABLE_KEY=...your publishable key...
rails s
```

If you add that script to your .gitingore then your keys won't be accidentally committed to the repository.

In production it will depend on your server. With Apache you can use SetEnv in your site config file. See http://httpd.apache.org/docs/2.4/mod/mod_env.html

**Comment by mazharoddin** [comment]
Thanks, I will try and let you know incase if I face any error.

**Comment by mazharoddin** [comment]
Hi, 
Now I am not getting STRIPE API Key related errors after I exported the keys using above script file, but still I unable to create account using signup option..can you please let me know I can signup. Thanks for your help.

**Comment by mazharoddin** [comment]
Hi, I could able to login using seeds file account...thanks

**Comment by buggy** [comment]
After loading the seed files you need to login to the admin and create a
new plan. You can then select that plan during the registration.

Rich

**Comment by mazharoddin** [comment]
Yeah , I could able to explore now, thanks for your time.
